language: scala
scala:
  - 2.12.6
jdk:
  - oraclejdk8

before_deploy: pip install --user release-manager==0.2.0
deploy:
  - provider: script
    script: release-manager --config .release.yml --make-artifact --upload-artifact --check-version
    skip_cleanup: true
    on:
      tags: true

env:
  global:
  # BINTRAY_SNOWPLOW_GENERIC_USER
  - secure: CjeFfuPIWpqcmqvAmZ6x5CQS7Rdg7BoT0ex8d9+NtvL3zDUoSPTw92d4cvrrbOWIu+MZqZQ4LvVfW+uN9OjBfne53WmqXjQ5MR3chdX0bQ6Oiy9qTCjcSxmNQbx+tGDzF/ZQ/mbWAd07XjQ5aFE3ENFi73nijDmC849Kin+yWr4llMJiuybfjYJQejC/RNNwUSz9Zr+zBQjEWOlau1J2PHlTtLbVA4NXEIi1QgPsb6rmdBRX9bIkSG15kedYq+Zp3QXNGJzds55D/c4uQD6/nIt2ACXjlE3rrRWVv2duNNmRcaip4s8tFKd6aqwCKdPwujSEXpkrk4TIq6dhSMA31182hxHOlT+5VjauPIDjMHWXQSI7pAlppCPPVCCgqv6E9GcYTLsqHuBSthLc0kSF+YihVVGZ1wrmzfsyyBIh+D87wTA/9CDtijl6gaZQ0wztGcuaa/3tlCE7FTszlwLO2a6OOkQ7DL0V//LseKpSJUBI8f9Uz6tjEIhIFrTxOVu4W6MUShfXsBoRZtKHkncfqA4rKwposzWm3D6TsePkIMe53zvsceMN8TQmNzWGESGzIom0HXfQGx4V2hjiLTTVmAFQm16nwYhWK+fDbwSVYEtUfw5XltAiNzpDgL/lzo19B/36gEmgzSbL9ZFLcsoCn0o+kxdmETl/iw9rEQ4LWcY=
  # BINTRAY_SNOWPLOW_GENERIC_API_KEY
  - secure: VZ21ouvj5gNjFMs41tz1ehy0peno7xWDZclEFpZlD4O0GXZZAKVrhATrIecRwtG0trPM1fQv5MO/GnEFPVpKVEaB7dm97Y9q9QI4aMo6NCvXnVwMUqmUZC0oTOdCOS3dEyRkv9f4xjS8652+rX3AGP6tLOlK0aVvFuLUjkwd4WegANbz47n+8wl7no+KAuJizfEcbUy5A0p4Uho6/1BPhpVYpTN09kSdcmFEVq8wzgFym49Mcn9hTzv0Zjzl7zYdRKyBp+t3SOjjVTpkDjHOSYL2R7Gk6XKAaOm42kD0Cst7ZR1W419aPG0zfA0a30Id7Mr3aA4YYfy7XjMZ7T2adUDmZzahak4Z97gyAVQy6UmkY7MJqt0Grly4y7RdMBP/kl2Shvn5QSK7zFtNBI1omnbzk5w1CU8+76Pa1+mQfGMjWXAYy4CEXY7A6dNM3erv92pAs9K91OHjL606sXgeeRejJEYTnXFec42A4eHmSxrR9SKA1R9nLulGWeWXCCJhbj9MiYJsmNuTZo6S53Z91/0GbvFLMXajba1qJGha8fys6EoovA5HpWb0FXHkhuS50fXFheyMhzrx6EsoSfXtOJGfcU45InoYSzXvny0dUPpu9dVPyIV5hnA8VasIy7lvre9sSU184G+ppzuOcR+ZyF/4VXh/Zd/kKrJ6xFajj+s=
